### ISSUE TITLE
Ring Topology

### ISSUE THREAD

**Issue by rumplestilzken** [scitrera/sparkrun#174]
NCCL_IB_MERGE_NICS=0
NCCL_IB_SUBNET_AWARE_ROUTING=1
NCCL_NET_PLUGIN=none

Need to be added to a .env to run on a ring topology. It is set up in spark-vllm-docker and nvidia's NCCL test script.

**Comment by dbotwinick** [comment]
Did you run `sparkrun setup` or `sparkrun setup wizard`? The sparkrun cluster definition needs to be configured to know if should use ring/mesh topology. It will only set the NCCL env vars properly for ring/mesh if the cluster is configured as ring/mesh.  

The setup wizard should verify the rest of your setup and also automatically detect topology.

**Comment by rumplestilzken** [comment]
I tried many times, i finally had luck with spark-vllm-docker with loading models.

I did try sparkrun setup and wizard at different times. 

There is a recipie i can run  in spark-vllm-docker but not in sparkrun as well. I thought this might be related?

**Comment by rumplestilzken** [comment]
I also used nvidia's playbook to configure cx7 btw, i updated an existing cluster --topology with ring and it seemed to get rid of some of my issues.

**Comment by dbotwinick** [comment]
Send the output of `sparkrun cluster inspect` so I can see your effective default settings. 
Try running a recipe with `sparkrun run <recipe> --collect-diagnostics diag.log` and send the diag.log along side whatever errors you get and I can try to diagnose. (That's easier than having a 15-step back and forth on the details).

The NVIDIA playbooks are unfortunately not always 100% or explain everything. I'm disappointed if the wizard didn't work for you, so I'd want to try to figure that out as well.

**Comment by rumplestilzken** [comment]
I'll get it to you in just a moment. 

I can take a snapshot of my system and set up fresh using sparkrun on a recipe from a hosted registry. However, there are none currently that support 3 nodes. It effectively uses Tensor Parallelism as 3 when you set Pipeline Parallelism to 3, according to VLLM boot up output.

**Comment by dbotwinick** [comment]
https://github.com/spark-arena/recipe-registry/blob/main/experimental-recipes/qwen3.5/vllm-mesh/qwen3.5-397b-a17b-int4-autoround-3x-vllm.yaml

That is a 3 node mesh recipe.

`sparkrun run @experimental/qwen3.5-397b-a17b-int4-autoround-3x-vllm`

assuming that your default cluster is configured properly in sparkrun. The recipes need to use pipeline_parallel:3 if you want to use pipeline parallelism. Most recipes by default use tensor parallelism.

**Comment by dbotwinick** [comment]
That's also a better template for you for v2 recipes. I recommend transitioning towards v2 recipes. It's a rocky transition because v1 recipe use became so widespread, but the long-term plan is for sparkrun and v2 recipes to replace run-recipe in eugr's spark-vllm0-docker repo.

(sparkrun does handle v1 recipes properly for backwards compatibility, but v2 is a bit cleaner and is part of shift towards more expressive functionality in the future).

**Comment by rumplestilzken** [comment]
One thing i noticed, is that sometimes it chose switch and sometimes chose ring when i used auto.

Also sometimes it used 127.0.0.1 and sometimes used 10.0.0.133

```
nick@spark-a669:~/dev/git/spark-vllm-docker$ sparkrun cluster inspect
Cluster Configuration:
  cluster:            ring
  ssh_user:           nick
  transfer_mode:      auto (resolved to: local)
  transfer_interface: auto (resolved to: cx7)
  topology:           ring
  hosts:              10.0.0.133, 10.0.0.134, 10.0.0.135

NCCL Environment (head: 10.0.0.133):
  GLOO_SOCKET_IFNAME=enP7s7
  MN_IF_NAME=enP7s7
  NCCL_CROSS_NIC=1
  NCCL_IB_DISABLE=0
  NCCL_IB_GID_INDEX=3
  NCCL_IB_HCA=rocep1s0f0,rocep1s0f1,roceP2p1s0f0,roceP2p1s0f1
  NCCL_IGNORE_CPU_AFFINITY=1
  NCCL_NET=IB
  NCCL_SOCKET_IFNAME=enP7s7,enp1s0f0np0,enp1s0f1np1,enP2p1s0f0np0,enP2p1s0f1np1
  NODE_IP=10.0.0.133
  OMPI_MCA_btl_tcp_if_include=enP7s7
  TP_SOCKET_IFNAME=enP7s7
  UCX_NET_DEVICES=rocep1s0f0:1,rocep1s0f1:1,roceP2p1s0f0:1,roceP2p1s0f1:1

Cache Paths:
  sparkrun (local):   /home/nick/.cache/sparkrun
  HF cache (local):   /home/nick/.cache/huggingface
  HF cache (remote):  /home/nick/.cache/huggingface

Directory Status:
  Host                           SR exists  SR size    HF exists  HF size    Free Space   HF path
  ----------------------------------------------------------------------------------------------------------------
  (local)                        yes        883M       yes        1.1T       1.3T         /home/nick/.cache/huggingface
  10.0.0.133                     yes        883M       yes        1.1T       1.3T         /home/nick/.cache/huggingface
  10.0.0.134                     no         -          yes        1.8T       1004G        /home/nick/.cache/huggingface
  10.0.0.135                     no         -          yes        2.9T       491G         /home/nick/.cache/huggingface

```


```
nick@spark-a669:~$ sparkrun run dev/git/dgx_spark_sparkrun_recipes/recipes/2xCluster/sehyo-Qwen3.5-122B-A10B-NVFP4.yaml  --collect-diagnostics diag.log
Note: 2 nodes required, using 2 of 3 hosts
sparkrun v0.2.31

Runtime:   vllm-ray
Image:     vllm-node-tf5
Model:     Sehyo/Qwen3.5-122B-A10B-NVFP4
Mode:      cluster (2 nodes)

VRAM Estimation:
  Model dtype:      compressed-tensors
  Model params:     40,744,136,364
  KV cache dtype:   fp8
  Architecture:     48 layers, 2 KV heads, 256 head_dim
  Model weights:    0.00 GB
  Tensor parallel:  2
  Per-GPU total:    0.00 GB
  DGX Spark fit:    YES

  GPU Memory Budget:
    gpu_memory_utilization: 89%
    Usable GPU memory:     107.7 GB (121 GB x 89%)
    Available for KV:      107.7 GB
    Max context tokens:    4,705,047
  Warning: Unknown dtype 'compressed-tensors'; cannot estimate model weight VRAM

Hosts:     default cluster 'ring'
  Head:    10.0.0.133
  Workers: 10.0.0.134

[1/6] Preparing
  done (1.0s)
[2/6] Building image
  done (0.0s)
[3/6] Distributing resources
  Distributing image vllm-node-tf5 to 2 host(s)
  Container image stale on 1 of 2 host(s), syncing
  Distributing model Sehyo/Qwen3.5-122B-A10B-NVFP4 to 2 host(s)
Fetching 16 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 96978.13it/s]
Download complete: : 0.00B [00:00, ?B/s]                Model synced to 2 host(s)                                                                          | 0/16 [00:00<?, ?it/s]
  done (293.8s)
[4/6] Syncing tuning configs
  done (0.0s)
[5/6] Launching vllm runtime
Download complete: : 0.00B [00:03, ?B/s]
  Step 1/5: Cleaning up existing containers
  Step 2/5: Detecting InfiniBand
  Step 3/5: Launching Ray head
  Step 4/5: Launching Ray workers
  Step 5/5: Executing serve command on head
  done (15.3s)
Cluster:   sparkrun_ff9dfdffa85d

Serve command:
  vllm serve Sehyo/Qwen3.5-122B-A10B-NVFP4  \
    --gpu-memory-utilization 0.89 \
    --port 8000 \
    --host 0.0.0.0 \
    --enable-prefix-caching \
    -tp 2  \
    --quantization compressed-tensors \
    --kv-cache-dtype fp8 \
    --load-format instanttensor \
    --max_num_batched_tokens 16384 \
    --max_num_seq 10 \
    --distributed-executor-backend ray

Runtime versions:
  build_base_image: nvidia/cuda:13.2.0-devel-ubuntu24.04
  build_build_args_build_jobs: 16
  build_build_args_exp_mxfp4: False
  build_build_args_transformers_5: True
  build_build_args_vllm_prs: 
  build_build_args_vllm_ref: main
  build_build_date: 2026-04-27 18:34:14+00:00
  build_build_script_commit: e3243bf55572d2281586dda313ed81838e4aa7bf
  build_flashinfer_commit: 5e1318cb
  build_gpu_arch: 12.1a
  build_vllm_commit: 2c06cf348
  build_vllm_version: 0.20.1rc1.dev4+g2c06cf348.d20260427.cu132
  container_maintainer: NVIDIA CORPORATION <cudatools@nvidia.com>
  container_org_opencontainers_image_ref_name: ubuntu
  container_org_opencontainers_image_version: 24.04
  cuda:      13.2
  nccl:      (2, 28, 9)
  python:    3.12.3
  torch:     2.11.0+cu130
  vllm:      0.20.1rc1.dev4+g2c06cf348.d20260427

[6/6] Post-launch hooks — skipped
(APIServer pid=934) INFO 05-16 05:42:32 [utils.py:299] 
(APIServer pid=934) INFO 05-16 05:42:32 [utils.py:299]        █     █     █▄   ▄█
(APIServer pid=934) INFO 05-16 05:42:32 [utils.py:299]  ▄▄ ▄█ █     █     █ ▀▄▀ █  version 0.20.1rc1.dev4+g2c06cf348.d20260427
(APIServer pid=934) INFO 05-16 05:42:32 [utils.py:299]   █▄█▀ █     █     █     █  model   Sehyo/Qwen3.5-122B-A10B-NVFP4
(APIServer pid=934) INFO 05-16 05:42:32 [utils.py:299]    ▀▀  ▀▀▀▀▀ ▀▀▀▀▀ ▀     ▀
(APIServer pid=934) INFO 05-16 05:42:32 [utils.py:299] 
(APIServer pid=934) INFO 05-16 05:42:32 [utils.py:233] non-default args: {'model_tag': 'Sehyo/Qwen3.5-122B-A10B-NVFP4', 'host': '0.0.0.0', 'model': 'Sehyo/Qwen3.5-122B-A10B-NVFP4', 'quantization': 'compressed-tensors', 'load_format': 'instanttensor', 'distributed_executor_backend': 'ray', 'tensor_parallel_size': 2, 'gpu_memory_utilization': 0.89, 'kv_cache_dtype': 'fp8', 'enable_prefix_caching': True, 'max_num_batched_tokens': 16384, 'max_num_seqs': 10}
(APIServer pid=934) INFO 05-16 05:42:32 [arg_utils.py:726] HF_HUB_OFFLINE is True, replace model_id [Sehyo/Qwen3.5-122B-A10B-NVFP4] to model_path [/cache/huggingface/hub/models--Sehyo--Qwen3.5-122B-A10B-NVFP4/snapshots/56a6bdda33285ba2d5688e4f71f6c714649497b4]
(APIServer pid=934) WARNING 05-16 05:42:32 [envs.py:1818] Unknown vLLM environment variable detected: VLLM_BASE_DIR
(APIServer pid=934) INFO 05-16 05:42:42 [nixl_utils.py:20] Setting UCX_RCACHE_MAX_UNRELEASED to '1024' to avoid a rare memory leak in UCX when using NIXL.
(APIServer pid=934) WARNING 05-16 05:42:42 [nixl_utils.py:34] NIXL is not available
(APIServer pid=934) WARNING 05-16 05:42:42 [nixl_utils.py:44] NIXL agent config is not available
(APIServer pid=934) INFO 05-16 05:42:42 [model.py:563] Resolved architecture: Qwen3_5MoeForConditionalGeneration
(APIServer pid=934) INFO 05-16 05:42:42 [model.py:1692] Using max model len 262144
(APIServer pid=934) INFO 05-16 05:42:43 [cache.py:261] Using fp8 data type to store kv cache. It reduces the GPU memory footprint and boosts the performance. Meanwhile, it may cause accuracy drop without a proper scaling factor
(APIServer pid=934) INFO 05-16 05:42:43 [scheduler.py:239] Chunked prefill is enabled with max_num_batched_tokens=16384.
(APIServer pid=934) WARNING 05-16 05:42:43 [config.py:367] Mamba cache mode is set to 'align' for Qwen3_5MoeForConditionalGeneration by default when prefix caching is enabled
(APIServer pid=934) INFO 05-16 05:42:43 [config.py:387] Warning: Prefix caching in Mamba cache 'align' mode is currently enabled. Its support for Mamba layers is experimental. Please report any issues you may observe.
(APIServer pid=934) WARNING 05-16 05:42:43 [vllm.py:831] Async scheduling will be disabled because it is not supported with the `ray` distributed executor backend. 
(APIServer pid=934) INFO 05-16 05:42:43 [vllm.py:840] Asynchronous scheduling is disabled.
(APIServer pid=934) INFO 05-16 05:42:43 [kernel.py:205] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'])
(APIServer pid=934) INFO 05-16 05:42:43 [compilation.py:303] Enabled custom fusions: act_quant
(APIServer pid=934) [transformers] `Qwen2VLImageProcessorFast` is deprecated. The `Fast` suffix for image processors has been removed; use `Qwen2VLImageProcessor` instead.
(APIServer pid=934) [transformers] The `use_fast` parameter is deprecated and will be removed in a future version. Use `backend="torchvision"` instead of `use_fast=True`, or `backend="pil"` instead of `use_fast=False`.
WARNING 05-16 05:42:58 [nixl_utils.py:34] NIXL is not available
WARNING 05-16 05:42:58 [nixl_utils.py:44] NIXL agent config is not available
(EngineCore pid=1181) INFO 05-16 05:42:58 [core.py:109] Initializing a V1 LLM engine (v0.20.1rc1.dev4+g2c06cf348.d20260427) with config: model='/cache/huggingface/hub/models--Sehyo--Qwen3.5-122B-A10B-NVFP4/snapshots/56a6bdda33285ba2d5688e4f71f6c714649497b4', speculative_config=None, tokenizer='/cache/huggingface/hub/models--Sehyo--Qwen3.5-122B-A10B-NVFP4/snapshots/56a6bdda33285ba2d5688e4f71f6c714649497b4', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=262144, download_dir=None, load_format=instanttensor, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=compressed-tensors, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=fp8, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=/cache/huggingface/hub/models--Sehyo--Qwen3.5-122B-A10B-NVFP4/snapshots/56a6bdda33285ba2d5688e4f71f6c714649497b4, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 16, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native']), enable_flashinfer_autotune=True, moe_backend='auto')
(EngineCore pid=1181) WARNING 05-16 05:42:58 [ray_utils.py:556] Tensor parallel size (2) exceeds available GPUs (1). This may result in Ray placement group allocation failures. Consider reducing tensor_parallel_size to 1 or less, or ensure your Ray cluster has 2 GPUs available.
(EngineCore pid=1181) 2026-05-16 05:42:58,748	INFO worker.py:1814 -- Connecting to existing Ray cluster at address: 10.0.0.133:46379...
(EngineCore pid=1181) 2026-05-16 05:42:58,755	INFO worker.py:2003 -- Connected to Ray cluster. View the dashboard at http://127.0.0.1:8265 
(EngineCore pid=1181) INFO 05-16 05:42:59 [ray_utils.py:621] No current placement group found. Creating a new placement group.
(EngineCore pid=1181) WARNING 05-16 05:42:59 [ray_utils.py:316] tensor_parallel_size=2 is bigger than a reserved number of GPUs (1 GPUs) in a node e71cec922f6fc412cfe9c16549b03d0c640749d4dc5fce637ecfbc7c. Tensor parallel workers can be spread out to 2+ nodes which can degrade the performance unless you have fast interconnect across nodes, like Infiniband. To resolve this issue, make sure you have more than 2 GPUs available at each node.
(EngineCore pid=1181) WARNING 05-16 05:42:59 [ray_utils.py:316] tensor_parallel_size=2 is bigger than a reserved number of GPUs (1 GPUs) in a node 132181130f3ecb64a765d4c8dc755105a2f1147a50ca7b06b5a591c4. Tensor parallel workers can be spread out to 2+ nodes which can degrade the performance unless you have fast interconnect across nodes, like Infiniband. To resolve this issue, make sure you have more than 2 GPUs available at each node.
(EngineCore pid=1181) INFO 05-16 05:43:09 [ray_env.py:100] Env var prefixes to copy: ['HF_', 'HUGGING_FACE_', 'LMCACHE_', 'NCCL_', 'UCX_', 'VLLM_']
(EngineCore pid=1181) INFO 05-16 05:43:09 [ray_env.py:101] Copying the following environment variables to workers: ['HF_HOME', 'HF_HUB_OFFLINE', 'LD_LIBRARY_PATH', 'MAX_JOBS', 'NCCL_CROSS_NIC', 'NCCL_IB_DISABLE', 'NCCL_IB_HCA', 'NCCL_IB_MERGE_NICS', 'NCCL_IB_SUBNET_AWARE_ROUTING', 'NCCL_IGNORE_CPU_AFFINITY', 'NCCL_NET', 'NCCL_NET_PLUGIN', 'NCCL_SOCKET_IFNAME', 'UCX_NET_DEVICES', 'UCX_RCACHE_MAX_UNRELEASED', 'VLLM_BASE_DIR', 'VLLM_WORKER_MULTIPROC_METHOD']
(EngineCore pid=1181) INFO 05-16 05:43:09 [ray_env.py:107] RAY_NON_CARRY_OVER_ENV_VARS from config: {'NODE_IP'}
(EngineCore pid=1181) INFO 05-16 05:43:09 [ray_env.py:111] To exclude env vars from copying, add them to /tmp/.config/vllm/ray_non_carry_over_env_vars.json
(EngineCore pid=1181) (RayWorkerWrapper pid=277, ip=10.0.0.134) WARNING 05-16 05:43:09 [system_utils.py:38] Overwriting environment variable LD_LIBRARY_PATH from '/usr/local/lib/python3.12/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64' to '/usr/local/lib/python3.12/dist-packages/cv2/../../lib64:/usr/local/lib/python3.12/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64'
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) WARNING 05-16 05:43:11 [nixl_utils.py:34] NIXL is not available
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) WARNING 05-16 05:43:11 [nixl_utils.py:44] NIXL agent config is not available
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) WARNING 05-16 05:43:11 [worker_base.py:292] Missing `shared_worker_lock` argument from executor. This argument is needed for mm_processor_cache_type='shm'.
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) INFO 05-16 05:43:11 [parallel_state.py:1402] world_size=2 rank=0 local_rank=0 distributed_init_method=tcp://10.0.0.133:49571 backend=nccl
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) INFO 05-16 05:43:14 [pynccl.py:111] vLLM is using nccl==2.29.7
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) WARNING 05-16 05:43:14 [symm_mem.py:66] SymmMemCommunicator: Device capability 12.1 not supported, communicator is not available.
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) WARNING 05-16 05:43:14 [custom_all_reduce.py:91] Custom allreduce is disabled because this process group spans across nodes.
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) WARNING 05-16 05:43:09 [system_utils.py:38] Overwriting environment variable LD_LIBRARY_PATH from '/usr/local/lib/python3.12/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64' to '/usr/local/lib/python3.12/dist-packages/cv2/../../lib64:/usr/local/lib/python3.12/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64'
(EngineCore pid=1181) (RayWorkerWrapper pid=277, ip=10.0.0.134) INFO 05-16 05:43:15 [parallel_state.py:1715] rank 1 in world size 2 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 1, EP rank 1, EPLB rank N/A
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136] EngineCore failed to start.
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136] Traceback (most recent call last):
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1110, in run_engine_core
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     engine_core = EngineCoreProc(*args, engine_index=dp_rank, **kwargs)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     return func(*args, **kwargs)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 876, in __init__
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     super().__init__(
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 118, in __init__
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     self.model_executor = executor_class(vllm_config)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     return func(*args, **kwargs)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/abstract.py", line 109, in __init__
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     self._init_executor()
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_executor.py", line 87, in _init_executor
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     self._init_workers_ray(placement_group)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_executor.py", line 376, in _init_workers_ray
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     self.collective_rpc("init_device")
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_executor.py", line 512, in collective_rpc
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     return ray.get(ray_worker_outputs, timeout=timeout)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     return fn(*args, **kwargs)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]            ^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/ray/_private/client_mode_hook.py", line 107, in wrapper
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     return func(*args, **kwargs)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 2980, in get
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     values, debugger_breakpoint = worker.get_objects(
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]                                   ^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 1023, in get_objects
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     raise value.as_instanceof_cause()
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136] ray.exceptions.RayTaskError(ValueError): ray::RayWorkerWrapper.execute_method() (pid=2286, ip=10.0.0.133, actor_id=ff3669cc5ffa25dee093f70a01000000, repr=<vllm.v1.executor.ray_utils.RayWorkerWrapper object at 0xeaf142e9ef30>)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_utils.py", line 90, in execute_method
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     raise e
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_utils.py", line 80, in execute_method
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     return run_method(self, method, args, kwargs)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/serial_utils.py", line 510, in run_method
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     return func(*args, **kwargs)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/worker_base.py", line 317, in init_device
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     self.worker.init_device()  # type: ignore
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     return func(*args, **kwargs)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 283, in init_device
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     self.requested_memory = request_memory(init_snapshot, self.cache_config)
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/utils.py", line 413, in request_memory
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136]     raise ValueError(
(EngineCore pid=1181) ERROR 05-16 05:43:15 [core.py:1136] ValueError: Free memory on device cuda:0 (107.04/121.69 GiB) on startup is less than desired GPU memory utilization (0.89, 108.3 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
(EngineCore pid=1181) Process EngineCore:
(EngineCore pid=1181) Traceback (most recent call last):
(EngineCore pid=1181)   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore pid=1181)     self.run()
(EngineCore pid=1181)   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
(EngineCore pid=1181)     self._target(*self._args, **self._kwargs)
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1140, in run_engine_core
(EngineCore pid=1181)     raise e
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1110, in run_engine_core
(EngineCore pid=1181)     engine_core = EngineCoreProc(*args, engine_index=dp_rank, **kwargs)
(EngineCore pid=1181)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=1181)     return func(*args, **kwargs)
(EngineCore pid=1181)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 876, in __init__
(EngineCore pid=1181)     super().__init__(
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 118, in __init__
(EngineCore pid=1181)     self.model_executor = executor_class(vllm_config)
(EngineCore pid=1181)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=1181)     return func(*args, **kwargs)
(EngineCore pid=1181)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/abstract.py", line 109, in __init__
(EngineCore pid=1181)     self._init_executor()
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_executor.py", line 87, in _init_executor
(EngineCore pid=1181)     self._init_workers_ray(placement_group)
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_executor.py", line 376, in _init_workers_ray
(EngineCore pid=1181)     self.collective_rpc("init_device")
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_executor.py", line 512, in collective_rpc
(EngineCore pid=1181)     return ray.get(ray_worker_outputs, timeout=timeout)
(EngineCore pid=1181)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
(EngineCore pid=1181)     return fn(*args, **kwargs)
(EngineCore pid=1181)            ^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/ray/_private/client_mode_hook.py", line 107, in wrapper
(EngineCore pid=1181)     return func(*args, **kwargs)
(EngineCore pid=1181)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 2980, in get
(EngineCore pid=1181)     values, debugger_breakpoint = worker.get_objects(
(EngineCore pid=1181)                                   ^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 1023, in get_objects
(EngineCore pid=1181)     raise value.as_instanceof_cause()
(EngineCore pid=1181) ray.exceptions.RayTaskError(ValueError): ray::RayWorkerWrapper.execute_method() (pid=2286, ip=10.0.0.133, actor_id=ff3669cc5ffa25dee093f70a01000000, repr=<vllm.v1.executor.ray_utils.RayWorkerWrapper object at 0xeaf142e9ef30>)
(EngineCore pid=1181)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_utils.py", line 90, in execute_method
(EngineCore pid=1181)     raise e
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_utils.py", line 80, in execute_method
(EngineCore pid=1181)     return run_method(self, method, args, kwargs)
(EngineCore pid=1181)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/serial_utils.py", line 510, in run_method
(EngineCore pid=1181)     return func(*args, **kwargs)
(EngineCore pid=1181)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/worker_base.py", line 317, in init_device
(EngineCore pid=1181)     self.worker.init_device()  # type: ignore
(EngineCore pid=1181)     ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=1181)     return func(*args, **kwargs)
(EngineCore pid=1181)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 283, in init_device
(EngineCore pid=1181)     self.requested_memory = request_memory(init_snapshot, self.cache_config)
(EngineCore pid=1181)                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/utils.py", line 413, in request_memory
(EngineCore pid=1181)     raise ValueError(
(EngineCore pid=1181) ValueError: Free memory on device cuda:0 (107.04/121.69 GiB) on startup is less than desired GPU memory utilization (0.89, 108.3 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
(EngineCore pid=1181) INFO 05-16 05:43:15 [ray_executor.py:110] Shutting down Ray distributed executor. If you see error log from logging.cc regarding SIGTERM received, please ignore because this is the expected termination process in Ray.
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89] Error executing method 'init_device'. This might cause deadlock in distributed execution.
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89] Traceback (most recent call last):
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_utils.py", line 80, in execute_method
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]     return run_method(self, method, args, kwargs)
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/serial_utils.py", line 510, in run_method
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]     return func(*args, **kwargs)
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]   File "/usr/local/lib/python3.12/dist-packages/ray/util/tracing/tracing_helper.py", line 461, in _resume_span
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]     return method(self, *_args, **_kwargs)
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/worker_base.py", line 317, in init_device
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]     self.worker.init_device()  # type: ignore
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]     ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]   File "/usr/local/lib/python3.12/dist-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]     return func(*args, **kwargs)
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 283, in init_device
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]     self.requested_memory = request_memory(init_snapshot, self.cache_config)
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/utils.py", line 413, in request_memory
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89]     raise ValueError(
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) ERROR 05-16 05:43:15 [ray_utils.py:89] ValueError: Free memory on device cuda:0 (107.04/121.69 GiB) on startup is less than desired GPU memory utilization (0.89, 108.3 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
(EngineCore pid=1181) (RayWorkerWrapper pid=277, ip=10.0.0.134) WARNING 05-16 05:43:11 [nixl_utils.py:34] NIXL is not available
(EngineCore pid=1181) (RayWorkerWrapper pid=277, ip=10.0.0.134) WARNING 05-16 05:43:11 [nixl_utils.py:44] NIXL agent config is not available
(EngineCore pid=1181) (RayWorkerWrapper pid=277, ip=10.0.0.134) WARNING 05-16 05:43:11 [worker_base.py:292] Missing `shared_worker_lock` argument from executor. This argument is needed for mm_processor_cache_type='shm'.
(EngineCore pid=1181) (RayWorkerWrapper pid=277, ip=10.0.0.134) INFO 05-16 05:43:12 [parallel_state.py:1402] world_size=2 rank=1 local_rank=0 distributed_init_method=tcp://10.0.0.133:49571 backend=nccl
(EngineCore pid=1181) (RayWorkerWrapper pid=277, ip=10.0.0.134) WARNING 05-16 05:43:14 [symm_mem.py:66] SymmMemCommunicator: Device capability 12.1 not supported, communicator is not available.
(EngineCore pid=1181) (RayWorkerWrapper pid=277, ip=10.0.0.134) WARNING 05-16 05:43:14 [custom_all_reduce.py:91] Custom allreduce is disabled because this process group spans across nodes.
(EngineCore pid=1181) (RayWorkerWrapper pid=2286) INFO 05-16 05:43:15 [parallel_state.py:1715] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0, EPLB rank N/A
(APIServer pid=934) Traceback (most recent call last):
(APIServer pid=934)   File "/usr/local/bin/vllm", line 10, in <module>
(APIServer pid=934)     sys.exit(main())
(APIServer pid=934)              ^^^^^^
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/cli/main.py", line 92, in main
(APIServer pid=934)     args.dispatch_function(args)
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/cli/serve.py", line 122, in cmd
(APIServer pid=934)     uvloop.run(run_server(args))
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 96, in run
(APIServer pid=934)     return __asyncio.run(
(APIServer pid=934)            ^^^^^^^^^^^^^^
(APIServer pid=934)   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
(APIServer pid=934)     return runner.run(main)
(APIServer pid=934)            ^^^^^^^^^^^^^^^^
(APIServer pid=934)   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
(APIServer pid=934)     return self._loop.run_until_complete(task)
(APIServer pid=934)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=934)   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 48, in wrapper
(APIServer pid=934)     return await main
(APIServer pid=934)            ^^^^^^^^^^
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 678, in run_server
(APIServer pid=934)     await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 692, in run_server_worker
(APIServer pid=934)     async with build_async_engine_client(
(APIServer pid=934)   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
(APIServer pid=934)     return await anext(self.gen)
(APIServer pid=934)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 100, in build_async_engine_client
(APIServer pid=934)     async with build_async_engine_client_from_engine_args(
(APIServer pid=934)   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
(APIServer pid=934)     return await anext(self.gen)
(APIServer pid=934)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 136, in build_async_engine_client_from_engine_args
(APIServer pid=934)     async_llm = AsyncLLM.from_vllm_config(
(APIServer pid=934)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 217, in from_vllm_config
(APIServer pid=934)     return cls(
(APIServer pid=934)            ^^^^
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 146, in __init__
(APIServer pid=934)     self.engine_core = EngineCoreClient.make_async_mp_client(
(APIServer pid=934)                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(APIServer pid=934)     return func(*args, **kwargs)
(APIServer pid=934)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 130, in make_async_mp_client
(APIServer pid=934)     return AsyncMPClient(*client_args)
(APIServer pid=934)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
(APIServer pid=934)     return func(*args, **kwargs)
(APIServer pid=934)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 900, in __init__
(APIServer pid=934)     super().__init__(
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 535, in __init__
(APIServer pid=934)     with launch_core_engines(
(APIServer pid=934)   File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
(APIServer pid=934)     next(self.gen)
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/utils.py", line 1119, in launch_core_engines
(APIServer pid=934)     wait_for_engine_startup(
(APIServer pid=934)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/utils.py", line 1178, in wait_for_engine_startup
(APIServer pid=934)     raise RuntimeError(
(APIServer pid=934) RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
```

The error here is my gpu-memory-utilization. But i got it working in spark-vllm-docker with that exact recipe. So that is confusing.

**Comment by rumplestilzken** [comment]
> https://github.com/spark-arena/recipe-registry/blob/main/experimental-recipes/qwen3.5/vllm-mesh/qwen3.5-397b-a17b-int4-autoround-3x-vllm.yaml
> 
> That is a 3 node mesh recipe.
> 
> `sparkrun run @experimental/qwen3.5-397b-a17b-int4-autoround-3x-vllm`
> 
> assuming that your default cluster is configured properly in sparkrun. The recipes need to use pipeline_parallel:3 if you want to use pipeline parallelism. Most recipes by default use tensor parallelism.

I'll look over the v2 and see what i can do with it. Thank you.

**Comment by dbotwinick** [comment]
> One thing i noticed, is that sometimes it chose switch and sometimes chose ring when i used auto.
> 
> Also sometimes it used 127.0.0.1 and sometimes used 10.0.0.133
> 
> ```
> nick@spark-a669:~/dev/git/spark-vllm-docker$ sparkrun cluster inspect
> Cluster Configuration:
>   cluster:            ring
>   ssh_user:           nick
>   transfer_mode:      auto (resolved to: local)
>   transfer_interface: auto (resolved to: cx7)
>   topology:           ring
>   hosts:              10.0.0.133, 10.0.0.134, 10.0.0.135
> 
> NCCL Environment (head: 10.0.0.133):
>   GLOO_SOCKET_IFNAME=enP7s7
>   MN_IF_NAME=enP7s7
>   NCCL_CROSS_NIC=1
>   NCCL_IB_DISABLE=0
>   NCCL_IB_GID_INDEX=3
>   NCCL_IB_HCA=rocep1s0f0,rocep1s0f1,roceP2p1s0f0,roceP2p1s0f1
>   NCCL_IGNORE_CPU_AFFINITY=1
>   NCCL_NET=IB
>   NCCL_SOCKET_IFNAME=enP7s7,enp1s0f0np0,enp1s0f1np1,enP2p1s0f0np0,enP2p1s0f1np1
>   NODE_IP=10.0.0.133
>   OMPI_MCA_btl_tcp_if_include=enP7s7
>   TP_SOCKET_IFNAME=enP7s7
>   UCX_NET_DEVICES=rocep1s0f0:1,rocep1s0f1:1,roceP2p1s0f0:1,roceP2p1s0f1:1
> 
> Cache Paths:
>   sparkrun (local):   /home/nick/.cache/sparkrun
>   HF cache (local):   /home/nick/.cache/huggingface
>   HF cache (remote):  /home/nick/.cache/huggingface
> 
> Directory Status:
>   Host                           SR exists  SR size    HF exists  HF size    Free Space   HF path
>   ----------------------------------------------------------------------------------------------------------------
>   (local)                        yes        883M       yes        1.1T       1.3T         /home/nick/.cache/huggingface
>   10.0.0.133                     yes        883M       yes        1.1T       1.3T         /home/nick/.cache/huggingface
>   10.0.0.134                     no         -          yes        1.8T       1004G        /home/nick/.cache/huggingface
>   10.0.0.135                     no         -          yes        2.9T       491G         /home/nick/.cache/huggingface
> ```

From this it's obvious that it's not functioning entirely properly in terms of respecting the mesh/ring configuration for the NCCL env vars, so that's troubling. I'll look at the full logs later and see what else I can find, but definitely a possible bug then in the mesh/ring topology part just from this much...

**Comment by dbotwinick** [comment]
As far as the memory part is concerned, you're 1GB shy from its calcs, so dropping the gpu utilization down a drop would do it OR you could reduce the max_num_batched_tokens a bit, it's predicting memory requirements including that I think, and 16384 is on the high side, so if you drop it to 8192, it might also squeak through the on memory side.

**Comment by rumplestilzken** [comment]
I have a 3 ring dgx cluster, so i can help debug if needed.

Still learning how to configure vllm to play nice, but i have gotten a half a dozen really large models running against OpenNotebook, i feed it a 62k context and see the expected result. So far Qwen3+ models have been the best.


When i tried talking to Gemini, it offered a possible solution by temporarily adding a listen address to (the second?) cx7 interface. Also, it suggested adding a route and doing some manual manipulation as it suggested the cx7 configuration often swapped the ip addresses on the 2nd interface.

I finally installled nvidia's solution and started using spark-vllm-docker and it just kinda worked - short of configuring for memory constraints.

**Comment by rumplestilzken** [comment]
I'm downloading 4 pretty hefty models at the moment from hf, so downloading the docker container is going to take a while. I'll get back to you on the v2 test.

**Comment by rumplestilzken** [comment]
https://github.com/rumplestilzken/dgx_spark_recipes/blob/main/recipes/3xRing/nvidia-Qwen3.5-397B-NVFP4-v2.yaml

Works as expected with v2.

**Comment by dbotwinick** [comment]
`sparkrun cluster inspect` had a bug, so it didn't reflect correctly. As you saw, it does work correctly in the inference/run path. 

Staged commit to fix `sparkrun cluster inspect` in the next release: https://github.com/spark-arena/sparkrun/commit/c0ceb1ab9de0f70d0382a2b885687b06f3e56806

**Comment by rumplestilzken** [comment]
[diag.log](https://github.com/user-attachments/files/27857747/diag.log)

In case you need it, here is the diag.log for the successful run.
